### ISSUE TITLE
Make it usable in CLJS too?

### ISSUE THREAD

**Issue by green-coder** [weavejester/ataraxy#17]
I really enjoy the declarativeness of Ataraxy. I hope it to be usable in front ends as well.

Since Ataraxy is purely functional, It feels like it would be possible to simply wrap a URL used by the front end into a dummy ring request and get useful match results, but I haven't try it yet.

Also, if used on the front end side, it would make sense to have a function to create a URL from a named route with its parameters (similarly to bidi).

**Comment by green-coder** [comment]
Note: maybe the dependency on the [`ring/ring-core`](https://github.com/weavejester/ataraxy/blob/9cae199db0ca44a4af4a78ff5cd1ea452275abbf/project.clj#L7) library can be more easily dropped by front-enders if [`ataraxy.core`](https://github.com/weavejester/ataraxy/blob/9cae199db0ca44a4af4a78ff5cd1ea452275abbf/src/ataraxy/core.clj#L8) does not use `:require` on `ataraxy.response`.

**Comment by weavejester** [comment]
I don't have any objections to this in principle, but it's unlikely that I'll personally have time to address this any time soon. ClojureScript support isn't a current priority for me.
