### ISSUE TITLE
Can not specify multiple different coercer

### ISSUE THREAD

**Issue by reedho** [weavejester/ataraxy#18]
This works:
```clojure
(ataraxy.core/compile*
 {["/api" #{id nr}] [:api ^int id ^int nr]}
 {}) 
;; => #object[ataraxy.core$eval22261$reify__22282 0x2ac04962 "ataraxy.core$eval22261$reify__22282@2ac04962"]
```

But If more than one symbol in the result be tagged with different coercer, route compile will fail.

```clojure
(ataraxy.core/compile*
 {["/api" #{id nr}] [:api ^int id ^uuid nr]}
 {})
```

Error shown is:

```text
Syntax error compiling fn* at (*cider-repl testx:localhost:64895(clj)*:29:1).
Cause: Unable to resolve classname: uuid
```

**Comment by weavejester** [comment]
Thanks for the report! I tracked it down to the tag metadata on symbols not being removed.

**Comment by reedho** [comment]
> Thanks for the report! I tracked it down to the tag metadata on symbols not being removed.

Awesome. Thank you.
