### ISSUE TITLE
cors middleware not supported(?)

### ISSUE THREAD

**Issue by teaforthecat** [weavejester/ataraxy#19]
Hi, it looks like a match must be made in order to call the middleware. I believe this means it is impossible to have cors requests because the preflight(options) request doesn't actually match any of the routes and so the middleware won't get called and ring-cors, for example, won't be able to send a response. 
Does that sound right?

**Comment by weavejester** [comment]
If you assign middleware to a particular route, yes that route needs to match for the middleware to be called. However, you can also assign middleware to the whole handler, before routing takes place.

**Comment by teaforthecat** [comment]
Yes, I have that working now, putting cors on the whole handler makes sense too. Thanks!
