### ISSUE TITLE
specify multiple middleware in serial?

### ISSUE THREAD

**Issue by bhurlow** [weavejester/ataraxy#2]
is possible to apply multiple middleware to a routing result? 

for example I want:
```
:routes {"/foo" ^:example ^:auth ^:login [:foo]}
```
(obviously not possible syntax but thats the idea)

**Comment by weavejester** [comment]
Yes, and the syntax you wrote in your comment is how you do it.

**Comment by weavejester** [comment]
A quick note: Clojure doesn't maintain order of metadata, so `^:a ^:b` is the same as `^:b ^:a`. To make the order deterministic, Ataraxy performs a sort on the keys.

**Comment by bhurlow** [comment]
Ah thanks. That would affect the application order of the middleware correct?

**Comment by weavejester** [comment]
Yep.

**Comment by viebel** [comment]
It seems weird to me to rely on the name of the keys to determine the order of the middleware. Is it a design choice or is it due to some constraints?

**Comment by weavejester** [comment]
The constraint is that metadata maps are unordered. 

I could always add an alternative syntax:

```clojure
:routes {^:middleware [:example :auth :login] [:foo]}
```

But I'd like to keep the current syntax as well, as it's much more concise when order doesn't matter.

**Comment by viebel** [comment]
I love the current syntax for cases when order doesn't matter.
It would be great if you could add support for the alternative syntax you suggested for cases when order does matter.
