### ISSUE TITLE
Cannot use kaocha-cloverage

### ISSUE THREAD

**Issue by carrete** [weavejester/ataraxy#25]
I get an error during the instrumentation phase when I attempt to run kaocha with the coverage plugin:

```
Execution error (NullPointerException) at ataraxy.core/wrap-handler$fn (core.clj:293).
Cannot invoke "clojure.lang.IFn.invoke(Object)" because "this.middleware_map" is null
```

The app runs without errors, as do the tests without the coverage plugin enabled.

**Comment by carrete** [comment]
For reference, https://github.com/lambdaisland/kaocha-cloverage

**Comment by weavejester** [comment]
Isn't this a kaocha-cloverage issue?

**Comment by carrete** [comment]
I assumed this was some sort of unintentional side-effect on import. Sorry for the noise

**Comment by carrete** [comment]
Turns out that middleware-map is indeed nil at https://github.com/weavejester/ataraxy/blob/master/src/ataraxy/core.clj#L293 when no middleware key is provided to `ataraxy/handler`. The diff below makes this error go away. No clue why this only seems to be a problem with kaocha-cloverage though. `(get middleware-map k)` could be a solution, but I'd still like to understand why this isn't a problem under "normal" usage. FYI

```diff
@@ -63,6 +63,7 @@
   (ataraxy/handler
    {:routes '{[:get "/dashboard"] [:dashboard]
               [:get "/dashboard-ws"] [:dashboard-ws]}
+    :middleware {}
     :handlers {:dashboard dashboard
                :dashboard-ws dashboard-ws}}))

```
