### ISSUE TITLE
Specify base routes

### ISSUE THREAD

**Issue by dpetranek** [weavejester/ataraxy#3]
Input:
    `(ataraxy.core/matches {"/" [:base-route]} {:uri "/"})` 

Expected output:
   `[:base-route]`

Actual output:
 `[:ataraxy.error/unmatched-path]`.

What's the best way to specify a base level route? I tried looking at the source (which is quite readable!), and I got confused by the macro part. I think (speculation) that strings should just be an equality check, and therefore not subject to the regex matching that the symbols go through. 

Any insight would be appreciated.

**Comment by weavejester** [comment]
I can't reproduce this error:

```clojure
user=> (require 'ataraxy.core)
nil
user=> (ataraxy.core/matches {"/" [:base-route]} {:uri "/"})
[:base-route]
```

Are you using Ataraxy 0.3.3?

**Comment by dpetranek** [comment]
Oh, I've just realized that I'm actually using duct/module.ataraxy "0.1.4" from the duct-alpha leiningen template. And when I upgrade that to 0.1.6, it works just fine. Thanks! I'll continue to enjoy this.
