### ISSUE TITLE
Support Switching Protocols

### ISSUE THREAD

**Issue by yueliangwen** [weavejester/ataraxy#4]
(defmethod handler/sync-default ::switch-protocols [{[_] :ataraxy/result}]
  {:status 101, :headers {}, :body nil})

should support **Switching Protocols** like this?

**Comment by weavejester** [comment]
To what end?

**Comment by yueliangwen** [comment]
Build websocket connection.

(defmethod ig/init-key ::init [_ options]
  (fn [req]
    (echo-handler req)
    [::switch-protocols]))

**Comment by weavejester** [comment]
You don't normally need to manually return an upgrade response. Servers like HTTP-Kit and Aleph will handle that for you when you switch from using HTTP to Websockets.

**Comment by yueliangwen** [comment]
Thank you for your response.
