### ISSUE TITLE
Set routes require top-level wrap-params

### ISSUE THREAD

**Issue by jamesnvc** [weavejester/ataraxy#8]
It seems that by default, routes using a set to specify query parameters fail to match, since they check `:query-params`, which requires `wrap-params` around the `ataraxy/handler`. This presumably should be documented?

**Comment by green-coder** [comment]
I stumbled across the same issue. Ring's spec provides the string:

```clojure
(:query-string req) ; => "q=aoeu"
```

while Ataraxy is matching its set routes based on that map instead:

```clojure
(:query-params req) ; => {"q" "aoeu"}
```

This should be documented in the README.md, somehow.

**Comment by weavejester** [comment]
Added an explanation to the README. Thanks for the report.
